//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenVueling.Infrastructure.Repository.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string role { get; set; }

        public Clients(string nombre, string email, string role)
        {
            this.nombre = nombre;
            this.email = email;
            this.role = role;
        }

        public Clients(System.Guid id, string nombre, string email, string role)
        {
            this.id = id;
            this.nombre = nombre;
            this.email = email;
            this.role = role;
        }

    }
}
